version: "2"
services:
  pool:
    build: .
    ports:
      - 8108:8008
      - 8188:8088
    volumes:
      - ./ethereum:/root/.ethereum
    environment:
      - VIRTUAL_HOST=eth.pool.claims
      - VIRTUAL_PORT=80
      - WALLET_PASSWORD_FILE_PATH=/root/.ethereum/password
    networks:
      - pool
      - rproxy

  redis:
    image: redis
    volumes:
      - ./redis:/data
    networks:
      - pool

networks:
  pool:
  rproxy:
    external:
      name: rproxy
